services:
    mysql:
        image: mysql:8
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql/

    app:
        build: .
        env_file:
            - .env
        labels:
            - "traefik.http.routers.backend-blue.rule=Host(`blue.docker.localhost`)"
            - "traefik.http.services.backend-blue.loadbalancer.server.port=8080"
        volumes:
            - ./laravel-project/storage/app:/app/storage/app
            - ./laravel-project/storage/logs:/app/storage/logs
        depends_on:
            - mysql

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - "15672:15672"
            - "5672:5672"

volumes:
    db_data:
        driver: local
