services:
    mysql:
        image: mysql:8
        tty: true
        environment:
            MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
            MYSQL_DATABASE: ${DB_DATABASE}
            MYSQL_USER: ${DB_USERNAME}
            MYSQL_PASSWORD: ${DB_PASSWORD}
        volumes:
            - db_data:/var/lib/mysql/

    traefik:
        image: traefik:v2.4
        ports:
            - "80:80"
            - "443:443"
            - "8080:8080"
        volumes:
            - ./traefik.yml:/etc/traefik/traefik.yml
            - ./dynamic:/etc/traefik/dynamic:ro

    backend-blue:
        image: derdek/laravel-bg-playground:latest
        env_file:
            - .env
        labels:
            - "traefik.http.routers.backend-blue.rule=Host(`blue.docker.localhost`)"
            - "traefik.http.services.backend-blue.loadbalancer.server.port=8080"
        volumes:
            - ./laravel-project/storage/app:/app/storage/app
            - ./laravel-project/storage/logs:/app/storage/logs
        depends_on:
            - mysql

    backend-green:
        image: derdek/laravel-bg-playground:latest
        env_file:
            - .env
        labels:
            - "traefik.http.routers.backend-green.rule=Host(`green.docker.localhost`)"
            - "traefik.http.services.backend-green.loadbalancer.server.port=8080"
        volumes:
            - ./laravel-project/storage/app:/app/storage/app
            - ./laravel-project/storage/logs:/app/storage/logs
        depends_on:
            - mysql

    rabbitmq:
        image: rabbitmq:3-management
        environment:
            - RABBITMQ_DEFAULT_USER=${RABBITMQ_DEFAULT_USER}
            - RABBITMQ_DEFAULT_PASS=${RABBITMQ_DEFAULT_PASS}
        ports:
            - "15672:15672"
            - "5672:5672"

    worker:
        build:
            context: .
            dockerfile: worker.Dockerfile
        env_file:
            - .env
        volumes:
            - ./laravel-project/storage/logs:/var/www/storage/logs
        stop_grace_period: 10m
        depends_on:
            - mysql
            - rabbitmq

    scheduler:
        build: .
        env_file:
            - .env
        volumes:
            - ./laravel-project/storage/logs:/app/storage/logs
        command: [ "php", "/app/artisan", "schedule:work" ]
        depends_on:
            - mysql
            - rabbitmq

    telegraf:
        image: telegraf:1.32-alpine
        hostname: ${TELEGRAF_HOSTNAME}
        user: telegraf:${DOCKER_GROUP_ID}
        environment:
            - INFLUX_TOKEN=${INFLUX_TOKEN}
        volumes:
            - ./telegraf.conf:/etc/telegraf/telegraf.conf:ro
            - /var/run/docker.sock:/var/run/docker.sock:ro

    pma:
        image: phpmyadmin/phpmyadmin
        environment:
            - PMA_HOST=mysql
            - PMA_USER=${DB_USERNAME}
            - PMA_PASSWORD=${DB_PASSWORD}
        ports:
            - "8181:80"
        depends_on:
            - mysql

volumes:
    db_data:
        driver: local
