services:
  mysql:
    image: mysql:8
    tty: true
    environment:
      MYSQL_ROOT_PASSWORD: ${DB_ROOT_PASSWORD}
      MYSQL_DATABASE: ${DB_DATABASE}
      MYSQL_USER: ${DB_USERNAME}
      MYSQL_PASSWORD: ${DB_PASSWORD}
    volumes:
      - db_data:/var/lib/mysql/

  backend:
    build: .
    env_file:
      - .env
    ports:
        - "8080:8080"
    volumes:
      - ./laravel-project:/app/
    depends_on:
      - mysql

  pma:
    image: phpmyadmin/phpmyadmin
    environment:
      - PMA_HOST=mysql
      - PMA_USER=${DB_USERNAME}
      - PMA_PASSWORD=${DB_PASSWORD}
    ports:
      - "8181:80"
    depends_on:
      - mysql

volumes:
  db_data:
    driver: local
